language: node_js

node_js:
  - lts/*

os:
  - windows
  - linux
  - osx

compiler:
  - gcc
  - clang

if: tag IS present

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libasound2 libpulse-dev libjack-dev ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install jack ; fi

before_script:
  - npm ci

script:
  - cd src
  - npm run build-binaries