language: node_js

node_js:
  - lts/*

os:
  - windows
  - linux
  - osx

dist: bionic

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libasound2 libasound2-dev libpulse-dev ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install asio4all ; fi

script:
  - cd src
  - npm ci

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npm run build-binaries
  on:
    tags: on