language: node_js

node_js:
  - lts/*

os:
  - windows
  - linux
  - osx

compiler:
  - gcc
  - clang

if: tag IS present

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; sudo apt-get install libasound2 ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; sudo apt-get install libpulse-dev ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; sudo apt-get install libjack-dev ; fi

  - if [ "$TRAVIS_OS_NAME" = "osx" ]; brew install jack ; fi

  - if [ "$TRAVIS_OS_NAME" = "windows" ]; echo upload=%GITHUB_TOKEN% > %HOMEDRIVE%%HOMEPATH%\.prebuildrc ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] || [ "$TRAVIS_OS_NAME" = "osx" ]; echo upload=$GITHUB_TOKEN > ~/.prebuildrc ; fi

script:
  - cd src
  - npm run build-binaries