language: node_js

node_js:
  - lts/*

os:
  - windows
  - linux
  - osx

compiler:
  - gcc
  - clang

if: tag IS present

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; sudo apt-get install libasound2 ; fi

script:
  - cd src
  - npm run build-binaries