name: Build && Deploy

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - { name: "Windows", os: windows-latest, cc: "cl", cxx: "cl" }
          - { name: "Ubuntu", os: ubuntu-latest, cc: "gcc", cxx: "g++" }
          - { name: "macOS", os: macos-latest, cc: "clang", cxx: "clang++" }

    steps:
      - name: Check-Out Code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm ci

      - name: Build Audify
        run: npm run build-binaries
        env:
          CMAKE_C_COMPILER: ${{ matrix.cc }}
          CMAKE_CXX_COMPILER: ${{ matrix.cxx }}
