name: Build && Deploy

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          # - { name: "Windows", os: windows-latest, arch: "amd64" }
          - { name: "Ubuntu (x64)", os: ubuntu-latest, arch: "amd64" }
          - { name: "Ubuntu (ARM64)", os: ubuntu-latest, arch: "arm64", cc: "aarch64-linux-gnu-gcc", cxx: "aarch64-linux-gnu-g++" }
          # - { name: "macOS", os: macos-latest, arch: "amd64" }

    env:
      CC: "${{ matrix.config.cc || '' }}"
      CXX: "${{ matrix.config.cxx || '' }}"
      BUILD_ARCH: "${{ matrix.config.arch != 'amd64' && matrix.config.arch || 'x64' }}"

    steps:
      - name: Check-Out Code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup CMake/Ninja
        uses: lukka/get-cmake@latest

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install Cross-Build Toolchain
        uses: awalsh128/cache-apt-pkgs-action@latest
        if: ${{ (runner.os == 'Linux') && (matrix.config.arch != 'amd64') }}
        with:
          packages: crossbuild-essential-${{ matrix.config.arch }}
          version: 1.0

      - name: Prepare Machine For Cross-Build
        if: ${{ (runner.os == 'Linux') && (matrix.config.arch != 'amd64') }}
        run: |
          sudo dpkg --add-architecture ${{ matrix.config.arch }}
          sudo sed -i 's#http://azure.archive.ubuntu.com/ubuntu#[arch=${{ matrix.config.arch }}] http://ports.ubuntu.com/ubuntu-ports#g' /etc/apt/sources.list

      - name: Install External Dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        if: runner.os == 'Linux'
        with:
          packages: libasound2:${{ matrix.config.arch }} libasound2-dev:${{ matrix.config.arch }} libpulse-dev:${{ matrix.config.arch }}
          version: 1.0

      - name: Install Audify Dependencies
        run: npm ci --ignore-scripts

      - name: Build Audify
        run: npm rebuild -- --arch ${{ env.BUILD_ARCH }}

      - name: Build Audify Prebuilt Binaries
        run: npm run build-binaries -- -- --arch ${{ env.BUILD_ARCH }}
