name: Commit Build

on:
  push:
    paths:
      - "src/**"
      - "vendor/**"
      - ".gitmodules"
      - "CMake**"
      - "**.js"
      - "**.ts"
      - "package-lock.json"
      - "tsconfig.json"
      - "!docs/**"

jobs:
  commit-build:
    uses: ./.github/workflows/build.yml
